In [28]:
import pandas as pd
import numpy as np

# Homework #4


The howework is due May 23rd 11:59PM.

## 1. Bike sharing dataset

This is a dataset of bike sharing data from 2011 and 2012 from Washington D.C. and is 
publicly available in [here](http://capitalbikeshare.com/system-data). Read the [README](./data/bike_sharing/Readme.txt) for details.

For this question, construct  

* a decision tree model
* a random forest
* a XGBoost tree model

to predict

1. the weather situation ('weathersit' column) using other columns.
2. the number of bikes ('cnt' column) using other columns.

# Answer 1

I uploaded the bike sharing data set to github and read it from github.

In [33]:
bike= pd.read_csv("https://raw.githubusercontent.com/deliormangokce/MATH555E-GitHub/main/day.csv")
bike

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0          1  2011-01-01       1   0     1        0        6           0   
1          2  2011-01-02       1   0     1        0        0           0   
2          3  2011-01-03       1   0     1        0        1           1   
3          4  2011-01-04       1   0     1        0        2           1   
4          5  2011-01-05       1   0     1        0        3           1   
..       ...         ...     ...  ..   ...      ...      ...         ...   
726      727  2012-12-27       1   1    12        0        4           1   
727      728  2012-12-28       1   1    12        0        5           1   
728      729  2012-12-29       1   1    12        0        6           0   
729      730  2012-12-30       1   1    12        0        0           0   
730      731  2012-12-31       1   1    12        0        1           1   

     weathersit      temp     atemp       hum  windspeed  casual  registered  \
0             2  0.344167  0.363625  0.805833   0.160446     331         654   
1             2  0.363478  0.353739  0.696087   0.248539     131         670   
2             1  0.196364  0.189405  0.437273   0.248309     120        1229   
3             1  0.200000  0.212122  0.590435   0.160296     108        1454   
4             1  0.226957  0.229270  0.436957   0.186900      82        1518   
..          ...       ...       ...       ...        ...     ...         ...   
726           2  0.254167  0.226642  0.652917   0.350133     247        1867   
727           2  0.253333  0.255046  0.590000   0.155471     644        2451   
728           2  0.253333  0.242400  0.752917   0.124383     159        1182   
729           1  0.255833  0.231700  0.483333   0.350754     364        1432   
730           2  0.215833  0.223487  0.577500   0.154846     439        2290   

      cnt  
0     985  
1     801  
2    1349  
3    1562  
4    1600  
..    ...  
726  2114  
727  3095  
728  1341  
729  1796  
730  2729  

[731 rows x 16 columns]

Packages

In [30]:
!pip install xgboost

In [54]:
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor 
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeRegressor
import xgboost

1)The weather situation ('weathersit' column) using other columns 

I deleted some variables(instant, dteday) from the data set. This is because I didn't use these variables for prediction.

In [35]:
Y = bike['weathersit']
X= bike
del X['weathersit']
del X['dteday']
del X['instant']

In [36]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.25, random_state = 0)

##model desicion tree
model = DecisionTreeClassifier(max_depth=3,criterion='entropy')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.7704918032786885

In [37]:
y_predict=model.predict(x_test)
print(y_predict)
conf_matrix= confusion_matrix(y_test, y_predict)
print(conf_matrix)

[1 1 1 3 2 3 2 2 1 2 1 2 2 1 1 1 1 1 1 2 1 2 1 1 2 1 1 1 1 1 1 1 2 1 2 1 1
 1 1 3 1 2 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 3 1 1 1 2 1 1 2 1
 1 2 1 1 1 1 1 1 1 1 2 1 1 1 2 1 2 1 1 1 2 2 3 1 2 1 2 1 3 1 1 1 1 1 1 3 1
 2 2 1 2 1 1 2 1 1 2 1 1 1 2 2 2 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 3
 1 1 1 2 1 3 3 1 1 1 3 3 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 2 1 1 2 3]
[[105   7   0]
 [ 22  31  10]
 [  1   2   5]]


27 observations have wrong estimation (except for the diagonals)

Lets continue with random forest:

In [38]:
##model random forest
classifier = RandomForestClassifier(n_estimators=15, criterion='entropy', random_state=0)
classifier.fit(x_train, y_train)
classifier.score(x_test, y_test)

0.7868852459016393

In [39]:
ypredict=classifier.predict(x_test)
print(ypredict)
conf_matrix= confusion_matrix(y_test, ypredict)
print(conf_matrix)

[1 1 1 2 2 3 2 2 1 2 1 2 2 1 1 1 1 1 1 2 1 2 1 1 2 1 1 1 1 1 1 1 2 1 2 1 1
 1 1 3 2 2 1 2 1 1 1 2 2 1 1 2 1 1 2 2 2 1 1 1 2 1 2 1 1 2 1 1 1 1 1 1 2 1
 1 2 1 1 1 1 1 1 1 1 2 1 1 2 2 2 2 1 1 1 2 2 3 1 1 1 2 1 2 1 1 1 1 1 2 2 2
 2 2 1 2 1 1 2 2 1 2 1 1 2 1 2 2 1 1 1 3 1 2 1 1 1 1 1 1 1 1 1 2 1 2 1 1 2
 1 1 1 2 1 2 1 1 1 1 2 2 1 1 2 2 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 2]
[[99 13  0]
 [18 43  2]
 [ 1  5  2]]


In [40]:
##model xgboost
xgboost_model = XGBClassifier(objective='binary:logistic', eval_metric='error')
xgboost_model.fit(x_train, y_train)

C:\Users\gokcedeliorman\Anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eval_metric='error',
              gamma=0, gpu_id=-1, importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=8,
              num_parallel_tree=1, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [41]:
yypredict=xgboost_model.predict(x_test)
print(yypredict)
conf_matrix= confusion_matrix(y_test, yypredict)
print(conf_matrix)

[1 1 1 2 2 3 2 2 1 2 1 2 2 1 1 1 1 1 1 2 1 2 1 1 2 1 2 1 1 1 1 1 2 1 2 1 1
 1 1 2 1 2 1 2 1 1 1 2 2 1 1 2 1 1 1 2 2 1 2 1 2 1 3 1 1 2 1 1 1 2 1 1 2 1
 1 2 1 1 2 1 1 1 1 1 2 1 1 2 2 2 1 1 1 1 2 2 3 2 2 1 2 1 3 1 1 1 1 1 1 2 2
 2 2 1 2 1 2 1 2 1 2 1 1 2 1 2 2 1 1 1 3 1 2 1 1 2 1 1 1 1 1 1 2 1 2 1 1 2
 1 1 1 1 1 3 3 1 1 1 3 3 1 1 2 2 1 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 2 2]
[[95 17  0]
 [18 40  5]
 [ 1  3  4]]


2) The number of bikes ('cnt' column) using other columns.

In [44]:
bike= pd.read_csv("https://raw.githubusercontent.com/deliormangokce/MATH555E-GitHub/main/day.csv")
Y2 = bike['cnt']
X2= bike
del X2['cnt']
del X2['dteday']
del X2['instant']
x_train,x_test,y_train,y_test = train_test_split(X2,Y2,test_size = 0.25, random_state = 0)

In [45]:
##model desicion tree
regressor = DecisionTreeRegressor()
regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [46]:
y_pred = regressor.predict(x_test)
pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})

Actual  Predicted
196    5923     5336.0
187    4592     4586.0
14     1248     1204.0
31     1360     1421.0
390    4075     4109.0
..      ...        ...
310    4035     4068.0
21      981      986.0
650    7282     7384.0
424    1834     1865.0
35     1005     1011.0

[183 rows x 2 columns]

In [48]:
##model random forest
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
rf.fit(x_train, y_train)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [49]:
rf.predict(x_test)

array([5553.21 , 4594.802, 1188.854, 1410.82 , 4060.973, 1871.089,
       2720.149, 6418.652, 6027.399, 1189.924, 1546.661, 1149.703,
       1464.331, 4848.312, 4355.264, 4030.219, 7506.014, 6597.847,
       3513.668, 2097.65 , 7624.383, 1448.737, 5340.146, 4441.39 ,
       1982.599, 4375.547, 3454.837, 4939.075, 7703.923, 7722.017,
        912.95 , 5095.426, 6538.41 , 5129.212, 2182.604, 4023.096,
       6816.275, 4602.534, 2801.485, 3034.159, 6555.411,  893.221,
       4842.536, 3554.305, 7500.078, 7483.629, 1965.024, 3248.488,
       2806.565, 1578.185, 5903.63 , 6876.558, 5591.57 , 7398.447,
       4576.257, 2891.337, 3638.012, 7495.193, 7066.523, 3305.703,
       7377.294, 4199.355, 4162.558, 7866.045, 7481.804, 2054.359,
       5174.97 , 5545.726, 6141.125, 5619.672, 6607.783, 7360.927,
       4851.416, 6613.584, 3331.02 , 6750.464, 5795.892, 6896.498,
       2432.329, 1881.413, 4421.863, 4915.809, 5359.349, 1643.683,
       4876.064, 7837.173, 4776.927, 6148.221, 4352.816, 4253.

In [52]:
error = abs(rf.predict(x_test) - y_test)
round(np.mean(error), 2)
mape = 100 * (error / y_test)
accuracy = 100 - np.mean(mape)
round(accuracy, 2)

97.67

In [55]:
##model xgboost
xgb = xgboost.XGBRegressor(n_estimators=100, learning_rate=0.08, gamma=0, subsample=0.75,colsample_bytree=1, max_depth=7)
xgb.fit(x_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.08, max_delta_step=0, max_depth=7,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.75,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [59]:
predictions = xgb.predict(x_test)
predictions

array([5669.227  , 4618.6787 , 1221.0673 , 1333.0702 , 4021.9658 ,
       1806.2924 , 2656.921  , 6316.576  , 6152.1753 , 1152.1394 ,
       1542.742  , 1153.4851 , 1394.4027 , 4794.0557 , 4372.6035 ,
       4058.2483 , 7458.6934 , 6592.6846 , 3433.7947 , 2070.6147 ,
       7660.1523 , 1299.5133 , 5313.419  , 4432.304  , 1935.591  ,
       4461.71   , 3363.606  , 5018.0864 , 7791.7163 , 7912.6865 ,
        883.19415, 5170.3433 , 6359.688  , 5199.9097 , 2030.0183 ,
       4000.807  , 6782.146  , 4671.0806 , 2781.0393 , 2856.8594 ,
       6730.108  ,  926.2635 , 4762.406  , 3480.8625 , 7487.7827 ,
       7404.6255 , 1968.77   , 2950.0837 , 2863.0767 , 1616.0581 ,
       5774.115  , 6839.884  , 5452.319  , 7433.152  , 4590.9043 ,
       2850.1033 , 3621.43   , 7484.931  , 7064.3    , 3310.3516 ,
       7306.5596 , 4146.3105 , 4136.286  , 8046.24   , 7491.5713 ,
       1879.9971 , 5196.1367 , 5273.3174 , 6163.2285 , 5666.0444 ,
       6577.892  , 7357.524  , 4842.682  , 6660.162  , 3213.60

## 2. Education datataset

This dataset is taken from [Kaggle](https://www.kaggle.com/spscientist/students-performance-in-exams). For this dataset, construct a decision tree regression and a XGBoost regression model to predict

1. math score
2. reading score
3. writing score

Beware: you might have to transform the data first before you train and test your models.

In [68]:
education = pd.read_csv("https://raw.githubusercontent.com/deliormangokce/MATH555E-GitHub/main/StudentsPerformance.csv")
education

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [69]:
education.info()
education.describe()
education['parental level of education'].describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


count             1000
unique               6
top       some college
freq               226
Name: parental level of education, dtype: object

In [88]:
X1=education['gender'].map({'female': 1, 'male': 2})
X2=education['race/ethnicity'].map({'group A': 1, 'group B': 2,'group C': 3,'group D': 4,'group E': 5})
X3=education['parental level of education'].map({"associate's degree": 1, 'some college': 2,'high school': 3,"master's degree": 4,"bachelor's degree": 5, 'some high school': 6})
X4=education['lunch'].map({'standard': 1, 'free/reduced': 2})
X5=education['test preparation course'].map({'completed': 1, 'none': 2})
Y1=education['math score']
Y2=education['reading score']
Y3=education['writing score']

data=(X1,X2,X3,X4,X5)
X=pd.DataFrame(data)
X=X.transpose()
X

gender  race/ethnicity  parental level of education  lunch  \
0         1               2                            5      1   
1         1               3                            2      1   
2         1               2                            4      1   
3         2               1                            1      2   
4         2               3                            2      1   
..      ...             ...                          ...    ...   
995       1               5                            4      1   
996       2               3                            3      2   
997       1               3                            3      2   
998       1               4                            2      1   
999       1               4                            2      2   

     test preparation course  
0                          2  
1                          1  
2                          2  
3                          2  
4                          2  
..                       ...  
995                        1  
996                        2  
997                        1  
998                        1  
999                        2  

[1000 rows x 5 columns]

In [89]:
##for Y1
xtrain,xtest,ytrain,ytest = train_test_split(X,Y1,test_size = 0.25, random_state = 0)

In [90]:
regressor = DecisionTreeRegressor()
regressor.fit(xtrain, ytrain)

DecisionTreeRegressor()

In [91]:
y1_pred = regressor.predict(xtest)

In [92]:
## xgb model for y1
xgb = xgboost.XGBRegressor(n_estimators=100, learning_rate=0.08, gamma=0, subsample=0.75,colsample_bytree=1, max_depth=7)
xgb.fit(xtrain,ytrain)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.08, max_delta_step=0, max_depth=7,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.75,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [93]:
predictions = xgb.predict(xtest)
pd.DataFrame({'Actual':ytest, 'XGBoost regr_predict':predictions, 'DecisionTree_predict':y1_pred})

Actual  XGBoost regr_predict  DecisionTree_predict
993      62             58.837509             60.000000
859      87             64.820221             64.200000
298      40             55.513241             53.000000
553      77             62.499073             61.666667
672      69             64.914917             65.133333
..      ...                   ...                   ...
462      71             82.683266             82.750000
356      63             62.549934             60.500000
2        90             74.270584             77.000000
478      55             66.487671             66.333333
695      79             58.492451             58.625000

[250 rows x 3 columns]

In [94]:
##for Y2
xtrain,xtest,ytrain,ytest = train_test_split(X,Y2,test_size = 0.25, random_state = 0)
regressor = DecisionTreeRegressor()
regressor.fit(xtrain, ytrain)
y2_pred = regressor.predict(xtest)

In [95]:
## xgb model for Y2
##model xgboost
xgb = xgboost.XGBRegressor(n_estimators=100, learning_rate=0.08, gamma=0, subsample=0.75,colsample_bytree=1, max_depth=7)
xgb.fit(xtrain,ytrain)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.08, max_delta_step=0, max_depth=7,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.75,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [96]:
predictions = xgb.predict(xtest)
pd.DataFrame({'Actual':ytest, 'XGBoost regr_predict':predictions, 'DecisionTree_predict':y2_pred})

Actual  XGBoost regr_predict  DecisionTree_predict
993      72             69.195595             70.000000
859      73             61.802067             61.400000
298      46             54.412521             51.000000
553      62             59.494606             58.666667
672      78             72.987869             72.866667
..      ...                   ...                   ...
462      70             81.654167             81.250000
356      61             56.393974             55.000000
2        95             83.691101             90.000000
478      64             74.289383             74.166667
695      89             68.287704             68.375000

[250 rows x 3 columns]

In [97]:
##for Y3
xtrain,xtest,ytrain,ytest = train_test_split(X,Y3,test_size = 0.25, random_state = 0)
regressor = DecisionTreeRegressor()
regressor.fit(xtrain, ytrain)
y3_pred = regressor.predict(xtest)
#pd.DataFrame({'Actual':ytest, 'Predicted':y3_pred})

In [98]:
## xgb model for Y3
xgb = xgboost.XGBRegressor(n_estimators=100, learning_rate=0.08, gamma=0, subsample=0.75,colsample_bytree=1, max_depth=7)
xgb.fit(xtrain,ytrain)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.08, max_delta_step=0, max_depth=7,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.75,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [99]:
predictions = xgb.predict(xtest)
pd.DataFrame({'Actual':ytest, 'XGBoost regr_predict':predictions, 'DecisionTree_predict':y2_pred})

Actual  XGBoost regr_predict  DecisionTree_predict
993      74             72.573380             70.000000
859      72             58.890347             61.400000
298      50             52.788559             51.000000
553      64             57.389652             58.666667
672      76             73.830475             72.866667
..      ...                   ...                   ...
462      76             82.374191             81.250000
356      61             50.550953             55.000000
2        93             80.943558             90.000000
478      70             77.743134             74.166667
695      86             68.285545             68.375000

[250 rows x 3 columns]

# 3. booking.com Challenge

This dataset is taken from [Booking.com Challenge ACM WSDM 2021](https://www.bookingchallenge.com/).

The original challenge was to predict the final destination city of the trip by looking at the data at hand for each user. For this question, you are free to do whatever you like. Do something interesting with the data :)

In [35]:
booking = pd.read_csv('./data/booking/train_set.csv')
booking

user_id     checkin    checkout  city_id device_class  affiliate_id  \
0        1000027  2016-08-13  2016-08-14     8183      desktop          7168   
1        1000027  2016-08-14  2016-08-16    15626      desktop          7168   
2        1000027  2016-08-16  2016-08-18    60902      desktop          7168   
3        1000027  2016-08-18  2016-08-21    30628      desktop           253   
4        1000033  2016-04-09  2016-04-11    38677       mobile           359   
...          ...         ...         ...      ...          ...           ...   
1166830   999855  2016-05-01  2016-05-02    20345       mobile           359   
1166831   999944  2016-06-23  2016-06-24    17944      desktop          4541   
1166832   999944  2016-06-24  2016-06-27    47075      desktop          2322   
1166833   999944  2016-06-27  2016-06-29      228      desktop           384   
1166834   999944  2016-06-29  2016-06-30    62930      desktop          4541   

        booker_country hotel_country   utrip_id  
0              Elbonia        Gondal  1000027_1  
1              Elbonia        Gondal  1000027_1  
2              Elbonia        Gondal  1000027_1  
3              Elbonia        Gondal  1000027_1  
4               Gondal  Cobra Island  1000033_1  
...                ...           ...        ...  
1166830         Gondal   Fook Island   999855_1  
1166831         Gondal  Glubbdubdrib   999944_1  
1166832         Gondal  Glubbdubdrib   999944_1  
1166833         Gondal  Glubbdubdrib   999944_1  
1166834         Gondal  Glubbdubdrib   999944_1  

[1166835 rows x 9 columns]

In [100]:
booking = pd.read_csv('C:\\Users\\gokcedeliorman\\Downloads\\train_set.csv')
booking

user_id     checkin    checkout  city_id device_class  affiliate_id  \
0        1000027  2016-08-13  2016-08-14     8183      desktop          7168   
1        1000027  2016-08-14  2016-08-16    15626      desktop          7168   
2        1000027  2016-08-16  2016-08-18    60902      desktop          7168   
3        1000027  2016-08-18  2016-08-21    30628      desktop           253   
4        1000033  2016-04-09  2016-04-11    38677       mobile           359   
...          ...         ...         ...      ...          ...           ...   
1166830   999855  2016-05-01  2016-05-02    20345       mobile           359   
1166831   999944  2016-06-23  2016-06-24    17944      desktop          4541   
1166832   999944  2016-06-24  2016-06-27    47075      desktop          2322   
1166833   999944  2016-06-27  2016-06-29      228      desktop           384   
1166834   999944  2016-06-29  2016-06-30    62930      desktop          4541   

        booker_country hotel_country   utrip_id  
0              Elbonia        Gondal  1000027_1  
1              Elbonia        Gondal  1000027_1  
2              Elbonia        Gondal  1000027_1  
3              Elbonia        Gondal  1000027_1  
4               Gondal  Cobra Island  1000033_1  
...                ...           ...        ...  
1166830         Gondal   Fook Island   999855_1  
1166831         Gondal  Glubbdubdrib   999944_1  
1166832         Gondal  Glubbdubdrib   999944_1  
1166833         Gondal  Glubbdubdrib   999944_1  
1166834         Gondal  Glubbdubdrib   999944_1  

[1166835 rows x 9 columns]

In [101]:
Y=booking['city_id']

In [102]:
booking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1166835 entries, 0 to 1166834
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype 
---  ------          --------------    ----- 
 0   user_id         1166835 non-null  int64 
 1   checkin         1166835 non-null  object
 2   checkout        1166835 non-null  object
 3   city_id         1166835 non-null  int64 
 4   device_class    1166835 non-null  object
 5   affiliate_id    1166835 non-null  int64 
 6   booker_country  1166835 non-null  object
 7   hotel_country   1166835 non-null  object
 8   utrip_id        1166835 non-null  object
dtypes: int64(3), object(6)
memory usage: 80.1+ MB


In [103]:
import statistics

In [104]:
print(statistics.multimode(booking['city_id']))
print(statistics.multimode(booking['booker_country']))
print(statistics.multimode(booking['hotel_country']))

[47499]
['Gondal']
['Cobra Island']


In [109]:
import datetime
from datetime import datetime
import dask.array as da
from dask import dataframe as dd

In [ ]:
#datetime.strptime(booking['checkout'][1], "%Y/%m/%d")
#booking['checkout']-booking['checkin']

In [106]:
unique_counts = pd.DataFrame.from_records([(col, booking[col].nunique()) for col in booking.columns],
                          columns=['Column_Name', 'Num_Unique']).sort_values(by=['Num_Unique'])

In [107]:
unique_counts

Column_Name  Num_Unique
4    device_class           3
6  booker_country           5
7   hotel_country         195
1         checkin         425
2        checkout         425
5    affiliate_id        3254
3         city_id       39901
0         user_id      200153
8        utrip_id      217686

When I tried something with booking data it took a lot of time :(

As I understand dask library is so popular for large data set.